services:
  crawler:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: crawler_service
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data
    environment:
      - MONGO_URI=mongodb://mongo:27017/news_db
    restart: always

  mongo:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: